// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwHnjHk0he5zGldTkMzbPjehDMFA0Hbas',
    appId: '1:585807019485:web:0dac905fe2a1b104898a34',
    messagingSenderId: '585807019485',
    projectId: 'finance-monitor-6e0f1',
    authDomain: 'finance-monitor-6e0f1.firebaseapp.com',
    storageBucket: 'finance-monitor-6e0f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLt06HjPn2ldJiCgFyKj3JcH9MT5vmFfs',
    appId: '1:585807019485:android:32a776c92972ae86898a34',
    messagingSenderId: '585807019485',
    projectId: 'finance-monitor-6e0f1',
    storageBucket: 'finance-monitor-6e0f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwiHLec1J-D2y-lvP7nR7niU7EYpHRAQ',
    appId: '1:585807019485:ios:c7313e696b21d3e6898a34',
    messagingSenderId: '585807019485',
    projectId: 'finance-monitor-6e0f1',
    storageBucket: 'finance-monitor-6e0f1.firebasestorage.app',
    iosBundleId: 'com.example.financeMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwiHLec1J-D2y-lvP7nR7niU7EYpHRAQ',
    appId: '1:585807019485:ios:c7313e696b21d3e6898a34',
    messagingSenderId: '585807019485',
    projectId: 'finance-monitor-6e0f1',
    storageBucket: 'finance-monitor-6e0f1.firebasestorage.app',
    iosBundleId: 'com.example.financeMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwHnjHk0he5zGldTkMzbPjehDMFA0Hbas',
    appId: '1:585807019485:web:49e11d7a30c4d16b898a34',
    messagingSenderId: '585807019485',
    projectId: 'finance-monitor-6e0f1',
    authDomain: 'finance-monitor-6e0f1.firebaseapp.com',
    storageBucket: 'finance-monitor-6e0f1.firebasestorage.app',
  );
}
